# Generated by Django 4.2.5 on 2023-09-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
